#!/usr/bin/env python3

import psutil

def get_cpu_info():
    freq_mhz = psutil.cpu_freq().max
    logical_cores = psutil.cpu_count(logical=True)

    if freq_mhz:
        freq_ghz = freq_mhz / 1000
        return f"{freq_ghz:.2f} GHz ({logical_cores} cores)"
    return f"N/A ({logical_cores} cores)"

def tigerfetch():
    cpu = get_cpu_info()
    
    print(f"CPU     {cpu}")

if __name__ == "__main__":
    tigerfetch()